backend/base/urls.py
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LogoutView
from django.urls import path

from .views import CustomLoginView, confirm_email, register, activate, password_reset_request, MainPageView, \
    CustomPasswordResetConfirmView, ProfileUpdateView, CustomPasswordChangeView

urlpatterns = [
    path('', MainPageView.as_view(), name='login'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='base:login'), name='logout'),
    path('register/', register, name='register'),
    path('confirm_email/', confirm_email, name='confirm_email'),
    path('activate/<uidb64>/<token>/', activate, name='activate'),
    path('profile_update/', ProfileUpdateView.as_view(), name='profile_update'),
    path('change_password/', CustomPasswordChangeView.as_view(),
         name='change_password'),
    path("password_reset/", password_reset_request, name="password_reset"),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='base/password/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         CustomPasswordResetConfirmView.as_view(
             template_name="base/password/password_reset_confirm.html"),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='base/password/password_reset_complete.html'),
         name='password_reset_complete'),
]

backend/job_analyzer/urls.py
from django.urls import path

from .views import MainPageJobAdvertisementList, details, update_fake_status, dashboard

urlpatterns = [
    path('', MainPageJobAdvertisementList.as_view(), name='main'),
    path('advertisement/<int:pk>/', details, name='advertisement'),
    path('dashboard/', dashboard, name='dashboard'),
    path('update_fake_status/', update_fake_status, name='update_fake_status')
]

backend/supervision_app/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('base.urls', 'base'), namespace='base')),
    path('analyzer/', include(('job_analyzer.urls', 'job_analyzer'), namespace='job_analyzer')),
]

backend/base/models.py
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    pass

    def __str__(self):
        return self.username

backend/job_analyzer/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class JobAdvertisement(models.Model):
    title = models.CharField(max_length=200, null=True, blank=True)
    content = models.TextField(null=True, blank=True)
    date_added = models.DateTimeField(null=True, blank=True)
    source_page = models.TextField(null=True, blank=True)
    date_of_account_creation = models.DateTimeField(null=True, blank=True)
    fake_probability = models.FloatField(null=True, blank=True)
    is_fake = models.BooleanField(default=False)

    class ProrityLevels(models.TextChoices):
        VERY_LOW = "1", _('Very Low')
        LOW = "2", _("Low")
        MEDIUM = "3", _("Medium")
        HIGH = '4', _("High")
        VERY_HIGH = '5', _("Very High")

    priority_level = models.CharField(
        max_length=1,
        choices=ProrityLevels.choices,
        default=ProrityLevels.MEDIUM,
    )

    def __str__(self):
        if self.date_added and self.source_page:
            return str(self.date_added) + " " + self.source_page
        else:
            return str(self.date_added) + " " + self.priority_level

    class Meta:
        order_with_respect_to = 'priority_level'

backend/base/forms.py
from django import forms
from django.contrib.auth.admin import UserAdmin as BaseUserAdmin
from django.contrib.auth.forms import UserChangeForm, UserCreationForm

from .models import CustomUser


class CustomUserChangeForm(UserChangeForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        password = self.fields.get("password")
        if password:
            password.help_text = 'Raw passwords are not stored, so there is no way to see this user’s password, ' \
                                 'but you can change the password using <a href="../change_password/">this form</a>.'

    class Meta:
        model = CustomUser
        fields = ("username", "email")


class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField(
        help_text='A valid email address, please.', required=True)

    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'password1', 'password2']

    def clean_email(self):
        if CustomUser.objects.filter(email=self.cleaned_data['email']).exists():
            raise forms.ValidationError(
                "The given email is already registered")
        return self.cleaned_data['email']

    def save(self, commit=True):
        user = super(UserRegistrationForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

backend/base/views.py
from django.contrib import messages
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.views import (LoginView, PasswordChangeView,
                                       PasswordResetConfirmView)
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import BadHeaderError, EmailMessage, send_mail
from django.db.models.query_utils import Q
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.views.generic import TemplateView, UpdateView

from .decorators import user_not_authenticated
from .forms import CustomUserChangeForm, UserRegistrationForm
from .models import CustomUser
from .tokens import account_activation_token


class MainPageView(TemplateView):
    template_name = "base/main.html"


class CustomLoginView(LoginView):
    template_name = "base/login.html"
    fields = '__all__'
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse_lazy('job_analyzer:main')

    def get_context_data(self, **kwargs):
        context = super(CustomLoginView, self).get_context_data()

        if 'email_confirmed' in self.request.session:
            context['email_confirmed'] = self.request.session['email_confirmed']
            del self.request.session['email_confirmed']
        return context


def confirm_email(request):
    return render(
        request=request,
        template_name="base/confirm_email.html",
    )


@user_not_authenticated
def register(request):
    if request.method == "POST":
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            activateEmail(request, user, form.cleaned_data.get('email'))
            return redirect('base:confirm_email')

        else:
            for error in list(form.errors.values()):
                messages.error(request, error)

    else:
        form = UserRegistrationForm()

    return render(
        request=request,
        template_name="base/register.html",
        context={"form": form}
    )


def password_reset_request(request):
    if request.method == "POST":
        password_reset_form = PasswordResetForm(request.POST)
        if password_reset_form.is_valid():
            data = password_reset_form.cleaned_data['email']
            associated_users = CustomUser.objects.filter(Q(email=data))
            if associated_users.exists():
                for user in associated_users:
                    subject = "Password Reset Requested"
                    email_template_name = "base/password/password_reset_email.txt"
                    c = {
                        "email": user.email,
                        'domain': '127.0.0.1:8000',
                        'site_name': 'Website',
                        "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                        "user": user,
                        'token': default_token_generator.make_token(user),
                        'protocol': 'http',
                    }
                    email = render_to_string(email_template_name, c)
                    try:
                        send_mail(subject, email, 'admin@student_helper.com',
                                  [user.email], fail_silently=False)
                    except BadHeaderError:
                        return HttpResponse('Invalid header found.')
                    return redirect("/password_reset/done/")
    password_reset_form = PasswordResetForm()
    return render(request=request, template_name="base/password/password_reset.html",
                  context={"password_reset_form": password_reset_form})


class CustomPasswordResetConfirmView(PasswordResetConfirmView):
    success_url = reverse_lazy("base:password_reset_complete")


def activateEmail(request, user, to_email):
    mail_subject = 'Activate your user account.'
    message = render_to_string('base/template_activate_account.html', {
        'user': user.username,
        'domain': get_current_site(request).domain,
        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
        'token': account_activation_token.make_token(user),
        'protocol': 'https' if request.is_secure() else 'http'
    })
    email = EmailMessage(mail_subject, message, to=[to_email])
    if email.send():

        return redirect('base.html')
        messages.success(request, f'Dear <b>{user}</b>, please go to you email <b>{to_email}</b> inbox and click on \
            received activation link to confirm and complete the registration. <b>Note:</b> Check your spam folder.')
    else:
        messages.error(
            request, f'Problem sending confirmation email to {to_email}, check if you typed it correctly.')


def activate(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = CustomUser.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, CustomUser.DoesNotExist):
        user = None

    print(user)
    print(account_activation_token.check_token(user, token))

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()

        request.session['email_confirmed'] = 'Thank you for your email confirmation. Now you can login into your ' \
                                             'account.'
        return redirect('base:login')
    else:
        messages.error(request, 'Activation link is invalid!')

    return redirect('job_analyzer:main')


class ProfileUpdateView(UpdateView):
    model = CustomUser
    form_class = CustomUserChangeForm
    template_name = 'base/user_update.html'
    success_url = reverse_lazy('job_analyzer:main')

    def get_object(self, *args, **kwargs):
        return self.request.user


class CustomPasswordChangeView(PasswordChangeView):
    template_name = "base/password/password_change.html"
    fields = '__all__'
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse_lazy('job_analyzer:main')

backend/job_analyzer/views.py
from datetime import datetime

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.shortcuts import render
from django.http import HttpResponse
from .models import JobAdvertisement

from typing import Any, Optional
import pandas as pd
from django.http.request import HttpRequest
from django.http.response import HttpResponse
from django.shortcuts import render
from django.views import View
from .utils import show_wordcloud, plot_priority, plot_fake


class MainPageJobAdvertisementList(LoginRequiredMixin, ListView):
    model = JobAdvertisement
    context_object_name = 'advertisements'
    template_name = 'job_analyzer/main.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['job_advertisements'] = JobAdvertisement.objects.order_by(
            'priority_level')

        date_added_from = self.request.GET.get('date_added_from')
        date_added_to = self.request.GET.get('date_added_to')
        priority_level = self.request.GET.get('priority_level')

        job_advertisements = JobAdvertisement.objects.all()

        if date_added_from and date_added_to:
            date_added_from = datetime.strptime(date_added_from, "%Y-%m-%d")
            date_added_to = datetime.strptime(date_added_to, "%Y-%m-%d")
            job_advertisements = job_advertisements.filter(
                date_added__range=(date_added_from, date_added_to))

        if priority_level:
            job_advertisements = job_advertisements.filter(
                priority_level=priority_level)

        context['job_advertisements'] = job_advertisements

        print(job_advertisements[0].priority_level)
        context['jobs_very_low'] = job_advertisements.filter(priority_level='Very Low').count()
        context['jobs_low'] = job_advertisements.filter(priority_level='Low').count()
        context['jobs_medium'] = job_advertisements.filter(priority_level='Medium').count()
        context['jobs_high'] = job_advertisements.filter(priority_level='High').count()
        context['jobs_very_high'] = job_advertisements.filter(priority_level='Very High').count()

        return context


def details(request, pk):
    job = JobAdvertisement.objects.get(id=pk)
    data = getattr(job, 'content')
    wordcloud = show_wordcloud(data)
    context = {'job': job,
               'wordcloud': wordcloud}
    return render(request, 'job_analyzer/advertisement.html', context)


def dashboard(request):
    jobs = JobAdvertisement.objects.all()
    fake = JobAdvertisement.objects.filter(is_fake=True)
    true = JobAdvertisement.objects.filter(is_fake=False)

    priority = [jobs.filter(priority_level='Very Low').count(),
                jobs.filter(priority_level='Low').count(),
                jobs.filter(priority_level='Medium').count(),
                jobs.filter(priority_level='High').count(),
                jobs.filter(priority_level='Very High').count()]

    priority_plot = plot_priority(priority)

    fake_plot = plot_fake([len(fake), len(true)])

    fake_string = ''
    for job in fake:
        fake_string += getattr(job, 'content')

    true_string = ''
    for job in true:
        true_string += getattr(job, 'content')

    fake_wordcloud = show_wordcloud(fake_string, color='white')
    true_wordcloud = show_wordcloud(true_string, color='white')

    context = {'n_jobs': len(jobs),
               'n_fake': len(fake),
               'priority_plot': priority_plot,
               'fake_plot': fake_plot,
               'fake_wordcloud': fake_wordcloud,
               'true_wordcloud': true_wordcloud}

    return render(request, 'job_analyzer/dashboard.html', context)

backend/job_analyzer/templates/job_analyzer/advertisement.html
{% extends 'job_analyzer/base.html' %} {% load static %} {% block content %}
<link rel="stylesheet" href="{% static 'job_analyzer/detail.css' %}"/>
<div id="title_div"><h1>Szczegóły ogłoszenia</h1></div>
<a href="{% url 'job_analyzer:main' %}">Powrót do listy</a>
<div class="row_div">
    <div class="col_div">
        <h2>{{ job.title }}</h2>
        <p>Data dodania: {{ job.date_added }}</p>
        <p>Strona źródłowa: {{ job.source_page }}</p>
        <p>Data założenia konta: {{ job.date_of_account_creation }}</p>
        <p>Priorytet: {{ job.get_priority_level_display }}</p>
        <p>Prawdopodobieństwo oszustwa: {{ job.fake_probability }}</p>
        <p id="content">Zawartość: {{ job.content }}</p>
    </div>

</div>
<div>
    {% if wordcloud is not None %}
        <img id="wordcloud" src="{{ wordcloud }}">
    {% endif %}
</div>
{% endblock content %}

backend/job_analyzer/templates/job_analyzer/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Analiza ofert</title>
    {% comment %}
    <link rel="icon" href="{% static 'todolist/to-do-list.png' %}" />
    {% endcomment %}
    <link rel="stylesheet" href="{% static 'job_analyzer/base.css' %}" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;1,300;1,400;1,700&display=swap"
      rel="stylesheet"
    />
    {% comment %}
    <link rel="stylesheet" href="{% static 'todolist/style.css' %}" />
    {% endcomment %}
  </head>
  <body>
    <div id="logo"><img src="https://supervisionhack.pl/wp-content/themes/supervision/img/logo.png" alt="logo"></div>
    <div class="wrapper">{% block content %} {% endblock content %}</div>
  </body>
</html>

backend/job_analyzer/templates/job_analyzer/dashboard.html
{% extends 'job_analyzer/base.html' %} {% load static %} {% block content %}
<link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
<link
        href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;1,300;1,400;1,700&display=swap"
        rel="stylesheet"
/>
<link rel="stylesheet" href="{% static 'job_analyzer/dashboard.css' %}"/>

<div id="navi"><a href="{% url 'job_analyzer:main'%}">Ogłoszenia</a></div>
<div id="title_div"><h1>Dashboard</h1></div>
<div id="container">
    <div id="stats">
        <span>Liczba ofert: {{n_jobs}}</span>
        <span>Liczba oszustw: {{n_fake}}</span>
    </div>
    <div id="plots">
        <div class="row">
            <div class="column"><img src="{{priority_plot}}"></div>
            <div class="column"><img src="{{fake_plot}}"></div>
        </div>
        <div class="row">
            <div class="column">
                <p>Oszustwa</p>
                {% if fake_wordcloud %}
                <img src="{{fake_wordcloud}}">
                {% else %}
                <p>Brak danych</p>
                {% endif %}
            </div>
            <div class="column">
                <p>Prawdziwe oferty</p>
                {% if true_wordcloud %}
                <img src="{{true_wordcloud}}">
                {% else %}
                <p>Brak danych</p>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock content %}

backend/job_analyzer/templates/job_analyzer/main.html
{% extends 'job_analyzer/base.html' %} {% load static %} {% block content %}
<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link
  href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;1,300;1,400;1,700&display=swap"
  rel="stylesheet"
/>
<link rel="stylesheet" href="{% static 'job_analyzer/jobs.css' %}" />
<div id="title_div"><h1>Ogłoszenia</h1></div>
<div id="filters">
  <form method="GET" action="">
    <label for="date_added_from">Filruj po dacie dodania:</label>
    <input type="date" id="date_added_from" name="date_added_from" />
    <span>to</span>
    <input type="date" id="date_added_to" name="date_added_to" />
    <br />
    <label for="priority_level">Filtruj po priorytecie:</label>
    <select id="priority_level" name="priority_level">
      <option value="">Wszystkie</option>
      <option value="Very Low">Bardzo niski</option>
      <option value="Low">Niski</option>
      <option value="Medium">Średni</option>
      <option value="High">Wysoki</option>
      <option value="Very High">Bardzo wysoki</option>
    </select>
    <br />
    <button type="submit">Zastosuj filtry</button>
  </form>
  <div class="statistics">
    <div class="statistics_wrapper">
      <div>Bardzo niski priorytet: {{ jobs_very_low}}</div>
      <div>Niski priorytet: {{ jobs_low }}</div>
      <div>Średni priorytet: {{ jobs_medium }}</div>
      <div>Wysoki priorytet: {{ jobs_high }}</div>
      <div>Bardzo wysoki priorytet: {{ jobs_very_high }}</div>
    </div>
  </div>
</div>
<div id="header_div">
  <div class="row_div">
    <div class="col_div">Tytuł</div>
    <div class="col_div">Zawartość</div>
    <div class="col_div">Data dodania</div>
    <div class="col_div">Strona źródłowa</div>
    <div class="col_div">Data założenia konta</div>
    <div class="col_div">Prawdopodobieństwo oszustwa</div>
    <div class="col_div">Priorytet</div>
    <div class="col_div">Czy oszustwo</div>
  </div>
</div>
<div id="jobs_div">
    {% for job in job_advertisements %}
    <div class="row_div">
        <div class="col_div"><p><a href="{% url 'job_analyzer:advertisement' job.id %}">{{ job.title }}</a></p></div>
        <div class="col_div" id="content"><p>{{ job.content }}</p></div>
        <div class="col_div"><p>{{ job.date_added }}</p></div>
        <div class="col_div"><p><a href="{{ job.source_page }}">{{job.source_page}}</a></p></div>
        <div class="col_div"><p>{{ job.date_of_account_creation }}</p></div>
        <div class="col_div"><p>{{ job.fake_probability }}</p></div>
        <div class="col_div"><p>{{ job.get_priority_level_display }}</p></div>
        {% comment %} <div class="col_div"><p>{{ job.is_fake }}</p></div> {% endcomment %}
        <div class="col_div">
          <p class="fake-status" data-job-id="{{ job.id }}" data-is-fake="{{ job.is_fake }}">
            {% if job.is_fake == True %}
              <span class="fake-label">Fake</span>
            {% elif job.is_fake == False %}
              <span class="fake-label">Real</span>
            {% endif %}
          </p>
        </div>
    </div>
  {% empty %}
  <div class="row_div">
    <div class="col_div">Empty</div>
  </div>
  {% endfor %}
</div>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
$(document).ready(function() {
  $('.fake-status').click(function() {
    var jobId = $(this).data('job-id');
    var isFake = $(this).data('is-fake');
    echo(jobId);
    echo(isFake);
    var newFakeStatus = !isFake; // Toggle the fake status

    $.ajax({
      url: 'update_fake_status/',
      type: 'POST',
      data: {
        job_id: jobId,
        is_fake: newFakeStatus
      },
      success: function() {
        // Update the UI with the new fake status
        if (newFakeStatus) {
          $(this).data('is-fake', True);
          $(this).find('.fake-label').tet('Fake');
        } else {
          $(this).data('is-fake', False);
          $(this).find('.fake-label').text('Real');
        }
        location.reload();
      },
      error: function(xhr, textStatus, errorThrown) {
        // Handle the error gracefully
        console.log('Error:', errorThrown);
      }
    });
  });
});
</script>

{% endblock content %}