backend/base/urls.py
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LogoutView
from django.urls import path

from .views import CustomLoginView, confirm_email, register, activate, password_reset_request, MainPageView, \
    CustomPasswordResetConfirmView, ProfileUpdateView, CustomPasswordChangeView

urlpatterns = [
    path('', MainPageView.as_view(), name='login'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='base:login'), name='logout'),
    path('register/', register, name='register'),
    path('confirm_email/', confirm_email, name='confirm_email'),
    path('activate/<uidb64>/<token>/', activate, name='activate'),
    path('profile_update/', ProfileUpdateView.as_view(), name='profile_update'),
    path('change_password/', CustomPasswordChangeView.as_view(),
         name='change_password'),
    path("password_reset/", password_reset_request, name="password_reset"),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='base/password/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         CustomPasswordResetConfirmView.as_view(
             template_name="base/password/password_reset_confirm.html"),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='base/password/password_reset_complete.html'),
         name='password_reset_complete'),
]

backend/job_analyzer/urls.py
from django.urls import path

from .views import MainPageJobAdvertisementList, details, update_fake_status, dashboard

urlpatterns = [
    path('', MainPageJobAdvertisementList.as_view(), name='main'),
    path('advertisement/<int:pk>/', details, name='advertisement'),
    path('dashboard/', dashboard, name='dashboard'),
    path('update_fake_status/', update_fake_status, name='update_fake_status')
]

backend/supervision_app/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('base.urls', 'base'), namespace='base')),
    path('analyzer/', include(('job_analyzer.urls', 'job_analyzer'), namespace='job_analyzer')),
]

backend/base/models.py
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    pass

    def __str__(self):
        return self.username

backend/base/forms.py
from django import forms
from django.contrib.auth.admin import UserAdmin as BaseUserAdmin
from django.contrib.auth.forms import UserChangeForm, UserCreationForm

from .models import CustomUser


class CustomUserChangeForm(UserChangeForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        password = self.fields.get("password")
        if password:
            password.help_text = 'Raw passwords are not stored, so there is no way to see this user’s password, ' \
                                 'but you can change the password using <a href="../change_password/">this form</a>.'

    class Meta:
        model = CustomUser
        fields = ("username", "email")


class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField(
        help_text='A valid email address, please.', required=True)

    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'password1', 'password2']

    def clean_email(self):
        if CustomUser.objects.filter(email=self.cleaned_data['email']).exists():
            raise forms.ValidationError(
                "The given email is already registered")
        return self.cleaned_data['email']

    def save(self, commit=True):
        user = super(UserRegistrationForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

backend/base/views.py
from django.contrib import messages
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.views import (LoginView, PasswordChangeView,
                                       PasswordResetConfirmView)
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import BadHeaderError, EmailMessage, send_mail
from django.db.models.query_utils import Q
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.views.generic import TemplateView, UpdateView

from .decorators import user_not_authenticated
from .forms import CustomUserChangeForm, UserRegistrationForm
from .models import CustomUser
from .tokens import account_activation_token


class MainPageView(TemplateView):
    template_name = "base/main.html"


class CustomLoginView(LoginView):
    template_name = "base/login.html"
    fields = '__all__'
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse_lazy('job_analyzer:main')

    def get_context_data(self, **kwargs):
        context = super(CustomLoginView, self).get_context_data()

        if 'email_confirmed' in self.request.session:
            context['email_confirmed'] = self.request.session['email_confirmed']
            del self.request.session['email_confirmed']
        return context


def confirm_email(request):
    return render(
        request=request,
        template_name="base/confirm_email.html",
    )


@user_not_authenticated
def register(request):
    if request.method == "POST":
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            activateEmail(request, user, form.cleaned_data.get('email'))
            return redirect('base:confirm_email')

        else:
            for error in list(form.errors.values()):
                messages.error(request, error)

    else:
        form = UserRegistrationForm()

    return render(
        request=request,
        template_name="base/register.html",
        context={"form": form}
    )


def password_reset_request(request):
    if request.method == "POST":
        password_reset_form = PasswordResetForm(request.POST)
        if password_reset_form.is_valid():
            data = password_reset_form.cleaned_data['email']
            associated_users = CustomUser.objects.filter(Q(email=data))
            if associated_users.exists():
                for user in associated_users:
                    subject = "Password Reset Requested"
                    email_template_name = "base/password/password_reset_email.txt"
                    c = {
                        "email": user.email,
                        'domain': '127.0.0.1:8000',
                        'site_name': 'Website',
                        "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                        "user": user,
                        'token': default_token_generator.make_token(user),
                        'protocol': 'http',
                    }
                    email = render_to_string(email_template_name, c)
                    try:
                        send_mail(subject, email, 'admin@student_helper.com',
                                  [user.email], fail_silently=False)
                    except BadHeaderError:
                        return HttpResponse('Invalid header found.')
                    return redirect("/password_reset/done/")
    password_reset_form = PasswordResetForm()
    return render(request=request, template_name="base/password/password_reset.html",
                  context={"password_reset_form": password_reset_form})


class CustomPasswordResetConfirmView(PasswordResetConfirmView):
    success_url = reverse_lazy("base:password_reset_complete")


def activateEmail(request, user, to_email):
    mail_subject = 'Activate your user account.'
    message = render_to_string('base/template_activate_account.html', {
        'user': user.username,
        'domain': get_current_site(request).domain,
        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
        'token': account_activation_token.make_token(user),
        'protocol': 'https' if request.is_secure() else 'http'
    })
    email = EmailMessage(mail_subject, message, to=[to_email])
    if email.send():

        return redirect('base.html')
        messages.success(request, f'Dear <b>{user}</b>, please go to you email <b>{to_email}</b> inbox and click on \
            received activation link to confirm and complete the registration. <b>Note:</b> Check your spam folder.')
    else:
        messages.error(
            request, f'Problem sending confirmation email to {to_email}, check if you typed it correctly.')


def activate(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = CustomUser.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, CustomUser.DoesNotExist):
        user = None

    print(user)
    print(account_activation_token.check_token(user, token))

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()

        request.session['email_confirmed'] = 'Thank you for your email confirmation. Now you can login into your ' \
                                             'account.'
        return redirect('base:login')
    else:
        messages.error(request, 'Activation link is invalid!')

    return redirect('job_analyzer:main')


class ProfileUpdateView(UpdateView):
    model = CustomUser
    form_class = CustomUserChangeForm
    template_name = 'base/user_update.html'
    success_url = reverse_lazy('job_analyzer:main')

    def get_object(self, *args, **kwargs):
        return self.request.user


class CustomPasswordChangeView(PasswordChangeView):
    template_name = "base/password/password_change.html"
    fields = '__all__'
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse_lazy('job_analyzer:main')

backend/base/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>FakeJob Hunter</title>
    <link rel="icon" href="{% static 'base/helper.png' %}" />
    <link rel="stylesheet" href="{% static 'base/base_style.css' %}" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;1,300;1,400;1,700&display=swap"
      rel="stylesheet"
    />
  </head>
  <body>
    <div id="logo"><img src="https://supervisionhack.pl/wp-content/themes/supervision/img/logo.png" alt="logo"></div>
    <div class="wrapper">{% block content %} {% endblock content %}</div>
  </body>
</html>

backend/base/templates/base/confirm_email.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
    <link rel="stylesheet" href="{% static 'base/confirm.css' %}">
    <div class="confirm">
        <h1>Confirm your email and proceed to login page.</h1>
        <div><a href="{% url 'base:login' %}">Login</a></div>
    </div>
{% endblock content %}

backend/base/templates/base/login.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
<div class="login-wrapper">
    <div class="form-wrapper">
        <h1>Login</h1>
        {% if email_confirmed %}
        <h3>{{ email_confirmed }}</h3>
        {% endif %}
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Login">
            <p class="forgot-password"><a href="{% url 'base:password_reset' %}">Forgot password?</a></p>
            <p class="no-account">Don't have an account? <br><a href="{% url 'base:register' %}">Register</a><br></p>
        </form>
    </div>
</div>
{% endblock content %}

backend/base/templates/base/main.html
{% extends 'base/base.html' %} {% load static %} {% block content %}
<link rel="stylesheet" href="{% static 'base/main.css' %}"/>
<div class="wrapper">
    <div id="main_text">
        <h1>Aplikacja do analizy ogłoszeń</h1>
        <p>Aplikacja umożliwia ściągnięcie ogłoszeń z popularnych serwisów ogłoszeniowych. Ściągnięte ogłoszenia
            poddawane są analizie oraz sprawdzane pod kątem bycia oszustwem. Aplikacja oferuje także dashboard, który
            podsumowuje ogłoszenia znajdujące się w bazie.</p>
        <div id="main_a">
            <a href="{% url 'base:login' %}" class="btn btn-primary">Zaloguj się</a>
        </div>
    </div>
</div>
{% endblock content %}

backend/base/templates/base/register.html
{% extends 'base/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<link rel="stylesheet" href="{% static 'base/register.css' %}">
<div class="login-wrapper">
    <div class="form-wrapper" id="register">
        <h1>Register</h1>
        <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" value="Register">
            <p id="account">Already have an account? <br><a href="{% url 'base:login' %}">Login</a></br></p>
        </form>
    </div>
</div>
{% endblock content %}

backend/base/templates/base/template_activate_account.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your registration:

http://{{ domain }}{% url 'base:activate' uidb64=uid token=token %}
{% endautoescape %}

backend/base/templates/base/user_update.html
{% extends 'base/base.html' %} {% load static %} {% block content %}
<link rel="preconnect" href="https://fonts.googleapis.com" /><link
  rel="preconnect"
  href="https://fonts.gstatic.com"
  crossorigin
/><link
  href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;1,300;1,400;1,700&display=swap"
  rel="stylesheet"
/>
<link rel="stylesheet" href="{% static 'base/profile_update.css' %}" />

<div class="profile-form-wrapper">
  <h3>Profile update</h3>
  <form method="POST">
    <a href="{% url 'job_analyzer:main' %}" class="back-button">Go back</a>
    {% csrf_token %} {{ form.as_p }}
    <input type="submit" value="Submit" />
  </form>
</div>
{% endblock content %}